# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.6'

services:

  # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "10000:10000" # Forward the exposed port 10000 on the container to port 10000 on the host machine
    restart: unless-stopped
    depends_on: 
      - rabbitmq # This service depends on rabbitmq. Start that first.
    environment: # Pass environment variables to the service
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  # Redis Service   
  rabbitmq:
    image: "rabbitmq:3-management" # Use a public RabbitMQ image to build the RabbitMQ service 
    ports:
      - "15672:15672"
      - "5673:5673"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:    